layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
#   sort_by options:
#     - pushed
  #   - stars
  limit: 12
  exclude:
    forks: false
#     projects:
    # - repo-name

social_media:
  facebook: liyasthomas
  linkedin: liyasthomas
  telegram: liyasthomas
  twitter: liyasthomas
  # vk: your_username

topics:
  - name: HTML
    web_url: https://github.com/topics/html
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/html/html.png

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: 3D

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

  - name: Web design

  - name: Firebase
    web_url: https://github.com/topics/firebase
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/firebase/firebase.png

  - name: Git
    web_url: https://github.com/topics/git
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/git/git.png

  - name: JSON
    web_url: https://github.com/topics/json
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/json/json.png

  - name: Material Design
    web_url: https://github.com/topics/material-design
    image_url: https://raw.githubusercontent.com/github/explore/ae6b22689282e8e8c3c43f9e82a0e80ff83423b6/topics/material-design/material-design.png

  - name: Node.js
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/fd96fceccf8c42c99cbe29cf0f8dcc4736fcb85a/topics/nodejs/nodejs.png

  - name: npm
    web_url: https://github.com/topics/npm
    image_url: https://raw.githubusercontent.com/github/explore/fd96fceccf8c42c99cbe29cf0f8dcc4736fcb85a/topics/npm/npm.png

  - name: PWA
    web_url: https://github.com/topics/pwa
    image_url: https://raw.githubusercontent.com/github/explore/698c66928eddcc6ad969b94912d7727c10229593/topics/pwa/pwa.png
